export const SET_USERS = 'SET_USERS';
export const SET_USERS_SUCCESS = 'SET_USERS_SUCCESS';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';

export const SET_VACATIONS = 'SET_VACATIONS';
export const FETCH_VACATIONS = 'FETCH_VACATIONS';
export const SET_VACATIONS_SUCCESS = 'SET_VACATIONS_SUCCESS';

export const SET_AVAILABLE_DAYS_SUCCESS = 'SET_AVAILABLE_DAYS_SUCCESS';
export const SET_AVAILABLE_DAYS_ERROR = 'SET_AVAILABLE_DAYS_ERROR';